name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y cmake gcc-multilib build-essential libsystemd-dev
    - uses: actions/checkout@v1
    - name: Run cmake
      run: cmake .
    - name: Run make
      run: make
